// Generated by https://quicktype.io

class People {
  int id;
  int document;
  String name;
  String lastName;
  String phone;
  String email;
  String password;
  String photo;
  String status;
  int userId;
  String createdAt;
  String updatedAt;

  People({
    required this.id,
    required this.document,
    required this.name,
    required this.lastName,
    required this.phone,
    required this.email,
    required this.password,
    required this.photo,
    required this.status,
    required this.userId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  String toString() {
    return '$name $lastName';
  }
}
