// Generated by https://quicktype.io

class Menu {
  final int id;
  final String name;
  final String description;
  final String status;
  final String? createdAt;
  final String? updatedAt;

  Menu({
    required this.id,
    required this.name,
    required this.description,
    required this.status,
    this.createdAt,
    this.updatedAt,
  });
}
