// Generated by https://quicktype.io

class PermissionPartial {
  final String? menuName;
  final int add;
  final int read;
  final int modify;
  final int remove;

  PermissionPartial({
    this.menuName,
    required this.add,
    required this.read,
    required this.modify,
    required this.remove,
  });
}
